apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: apps
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      serviceAccountName: large-dev-app-sa
      containers:
      - name: lds-web-app-backend
        image: georgezudikhin/lds-web-app-backend:latest
        ports:
        - containerPort: 8080