apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx2
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/GeorgeZudikhin/large-dev-argo.git"
    path: "root-app/apps/nginx2"
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
        - values-secrets.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true