apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app
  namespace: apps
spec:
  project: default
  source:
    repoURL: https://github.com/GeorgeZudikhin/large-dev-argo.git
    path: root-app
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: apps
  syncPolicy:
    automated:
      selfHeal: true
      prune: true