kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: devices
  name: large-dev-app-role
rules:
- apiGroups: [""]
  resources: ["pods", "services"]
  verbs: ["get", "list", "create", "delete"]