apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: large-dev-app-role-binding
  namespace: devices
subjects:
- kind: ServiceAccount
  name: large-dev-app-sa
  namespace: apps
roleRef:
  kind: Role
  name: large-dev-app-role
  apiGroup: rbac.authorization.k8s.io