apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: large-dev-ingress
  namespace: argocd
spec:
  rules:
  - host: argocd.large-dev.zapto.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: argocd-server
            port:
              number: 80