argo-cd:
  server:
  nodeSelector:
    worker.gardener.cloud/pool: np-ske

  repoServer:
    nodeSelector:
      worker.gardener.cloud/pool: np-ske

  applicationController:
    nodeSelector:
      worker.gardener.cloud/pool: np-ske

  dex:
    nodeSelector:
      worker.gardener.cloud/pool: np-ske
