argo-cd:
  configs:
    cm:
      admin.enabled: true
      url: https://argocd.ldevice.servicedesk.tvwebservices.org
      dex.config: |
        logger:
          level: info
          format: json
        connectors:
        - type: saml
          id: saml
          name: SAML
          config:
            entityIssuer: https://argocd.ldevice.servicedesk.tvwebservices.org/api/dex/callback
            ssoURL: https://login.microsoftonline.com/ff009f2c-d651-472e-b73e-e0f894c6011e/saml2
            caData: |
              LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tDQpNSUlDOERDQ0FkaWdBd0lCQWdJUVhIQXJVb21U
              d29WUDJKVzNTVGhTUVRBTkJna3Foa2lHOXcwQkFRc0ZBREEwDQpNVEl3TUFZRFZRUURFeWxOYVdO
              eWIzTnZablFnUVhwMWNtVWdSbVZrWlhKaGRHVmtJRk5UVHlCRFpYSjBhV1pwDQpZMkYwWlRBZUZ3
              MHlOREEzTWpVd09EVTNOREZhRncweU56QTNNalV3T0RVM05ERmFNRFF4TWpBd0JnTlZCQU1UDQpL
              VTFwWTNKdmMyOW1kQ0JCZW5WeVpTQkdaV1JsY21GMFpXUWdVMU5QSUVObGNuUnBabWxqWVhSbE1J
              SUJJakFODQpCZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUF0UFJhY2RSV2h4QzBy
              SlhEN0srVjFmZlEwMDZmDQpTN25CZ3BLeXVWSitsR3pOYUg5cUF1cGV1NCtiSDVMdkRZazdlTVZw
              aEhqeWlTeXh1QXVGeXo3dEYyR1VBdjdLDQpqVnlIeXlNYjNycVd6R3FoTlBxMjlzOTAxc2FqMmFw
              b09ZMjFoMjcyTEFpN09YRXlGUHBXS3R5RHJGUlpjZDhHDQplaG5PQlNidFoxTERyTXJNL3hJZXdv
              NnB2cDkvK21vMTRGb29KWjFtQXo2bGlhelJCRVlvZ1VYM1oxU0NpU2dXDQowWHZKZ09YalM3R2Vv
              ZFRGb29hbXBvK3diQXBZUFh6RGF0dHlyNVRGZ2QveXRTK0dBUkFwcVVNZFh1OUpUM3pnDQpTZHNh
              MmlEVi9RbzhOL1ptLy8xWlRqRE1mK1hjWk9jNFlaUWw0K1NnWnF6RjZCU0J3eWpTcCszMndRSURB
              UUFCDQpNQTBHQ1NxR1NJYjNEUUVCQ3dVQUE0SUJBUUFmZjdpNWdMNHFkZVkxTFYxZzFTdlpMZkR4
              T1ROTU03a3pYL05ZDQpSZ0wwb0l0QVVORGJMQlpRWEZxdlhtMTFTYWVWRmZ4Tk5pVWRkNzMwTk5I
              N0pYN29NT0lVem8rNFZmV2piK0RFDQoxL2JEU283emZOOXQ5akJrWFhjYS9YZzc5MzRKK3hqVmND
              bThVVFFpVHllYjEwYytPWmI0N1JRdUNjRVlMdG1zDQphOGpWNHdlM3ljN1d0NWdxWlZQYmtkVTQ2
              U0wrMDFVQnU0NTFUd1BtZFlta1JMdTlublBkVGxSWGJyWnd2eGdpDQpIdW1zZ2JqS0RXbHZaUlJ0
              YXJBcE10TVcwYzhJdUpDRE1lQ2ZJdnFna0IxWWFzTW5RM0lSV0VaNHZlbjc4V2h3DQpBMTV5c24y
              Vmttd3NPbGpSamNWanIwbHV6bTBvdjJCNkpyRnd2aU8vak1VM0xCaWYNCi0tLS0tRU5EIENFUlRJ
              RklDQVRFLS0tLS0NCg==
            redirectURI: https://argocd.ldevice.servicedesk.tvwebservices.org/api/dex/callback
            usernameAttr: email
            emailAttr: email
            groupsAttr: Group
    rbac:
      policy.csv: |
        p, role:admin, applications, *, */*, allow
        p, role:admin, repositories, *, */*, allow
        p, role:admin, clusters, *, */*, allow
        p, role:readonly, applications, get, */*, allow
        g, "f6e6eb76-7a3a-4193-8fdb-2b9e78307fe3", role:admin
        g, "6f4314bd-6f87-452f-8aa9-136867baff46", role:readonly

  notifications:
    enabled: false
  applicationSet:
    enabled: false
  server:
    extraArgs:
      - --insecure
    nodeSelector:
      worker.gardener.cloud/pool: np-ske
  repoServer:
    nodeSelector:
      worker.gardener.cloud/pool: np-ske
  applicationController:
    nodeSelector:
      worker.gardener.cloud/pool: np-ske
  dex:
    nodeSelector:
      worker.gardener.cloud/pool: np-ske