argo-cd:
  notifications:
    enabled: false
  applicationSet:
    enabled: false
  server:
    extraArgs:
      - --insecure
    nodeSelector:
      nodepool: np-ske
  repoServer:
    nodeSelector:
      nodepool: np-ske
  applicationController:
    nodeSelector:
      nodepool: np-ske
  dex:
    nodeSelector:
      nodepool: np-ske