# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: large-dev-ingress
#   namespace: argocd
# spec:
#   ingressClassName: nginx
#   rules:
#   - host: argocd.large-dev.zapto.org
#     http:
#       paths:
#       - path: /
#         pathType: Prefix
#         backend:
#           service:
#             name: argo-cd-argocd-server
#             port:
#               number: 80
#   - host: web-app.large-dev.zapto.org
#     http:
#       paths:
#       - path: /
#         pathType: Prefix
#         backend:
#           service:
#             name: nginx
#             port:
#               number: 80

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: large-dev-ingress
  namespace: argocd
spec:
  ingressClassName: nginx
  rules:
  - host: large-dev.zapto.org
    http:
      paths:
      - path: /argocd
        pathType: Prefix
        backend:
          service:
            name: argo-cd-argocd-server
            port:
              number: 80
      - path: /web-app
        pathType: Prefix
        backend:
          service:
            name: nginx
            port:
              number: 80